version: '2'
services:
    vyka-app:
        image: saran4krish/vyka
        environment:
            - SPRING_PROFILES_ACTIVE=dev,swagger
            - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/eureka
            - SPRING_CLOUD_CONFIG_URI=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/config
            - SPRING_DATASOURCE_URL=jdbc:mysql://vyka-mysql:3306/vyka?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=60 # gives time for the JHipster Registry to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=vyka-elasticsearch:9300
            - EUREKA_CLIENT_ENABLED=true
            - JHIPSTER_CACHE_HAZELCAST_MANAGEMENT-CENTER_URL=http://vyka-hazelcast-management-center:1111/mancenter

        ports:
            - 8080:8080
        depends_on:
            - vyka-mysql
            - jhipster-registry
    vyka-mysql:
        extends:
            file: mysql.yml
            service: vyka-mysql
    vyka-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: vyka-elasticsearch
    jhipster-registry:
        extends:
            file: jhipster-registry.yml
            service: jhipster-registry
        environment:
            - SPRING_CLOUD_CONFIG_SERVER_NATIVE_SEARCH_LOCATIONS=file:./central-config/docker-config/
    vyka-hazelcast-management-center:
        extends:
            file: hazelcast-management-center.yml
            service: vyka-hazelcast-management-center