version: '2'
services:
    vyka-mysql:
        image: mysql:5.7.20
        volumes:
             - /usr/local/mysql/data:/var/lib/mysql/
        environment:
            - MYSQL_USER=root
            #- MYSQL_ALLOW_EMPTY_PASSWORD=yes
            - MYSQL_PASSWORD=root
            - MYSQL_DATABASE=vyka
        ports:
            - 3306:3306
        command: mysqld --lower_case_table_names=1 --skip-ssl --character_set_server=utf8 --explicit_defaults_for_timestamp
